framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    assets: ~
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    router:
        utf8: true
