security:
    enable_authenticator_manager: true
    password_hashers:
        App\\Entity\\AdminUser:
            algorithm: auto
    providers:
        admin_provider:
            entity:
                class: App\\Entity\\AdminUser
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            provider: admin_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: admin_dashboard
            logout:
                path: app_logout
                target: /admin/login
    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
