version: "3.9"

services:
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    environment:
      SSL_CERT_COMMON_NAME: ${SSL_CERT_COMMON_NAME:-localhost}
