services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/AdminKernel.php'

    App\Service\TelegramNotifier:
        arguments:
            $token: '%env(default::TELEGRAM_BOT_TOKEN)%'
            $chatId: '%env(default::TELEGRAM_CHAT_ID)%'
