# Update the "app" value with your Fly.io application name
app = "story-song"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[fly_launch]
  # Update both "app_name" and "org" to match your Fly.io project.
  app_name = "story-song"
  org = "personal"
  # The GitHub build pipeline expects the Machines platform.
  platform_version = "machines"
