name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run remote deployment
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull
            docker compose up -d --build php nginx
